spring.application.name=chisme-chat

# Configuración H2 en memoria
spring.datasource.url=jdbc:h2:mem:paypro;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Consola H2 habilitada
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=mysuperlongsecretkeythatshouldbeatleast64byteslongandrandomtouseinthe512signaturealgorithm
jwt.expirationMs=86400000
server.port=8080

paypro.api-key=secret123
# paypro:
#   api-key: secret123

# Apagar SQL en dev
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF
logging.level.org.hibernate.engine.jdbc.spi.SqlStatementLogger=OFF

# Habilitar tracing - opentelemtry - ver en http://localhost:16686/
#deshabilitar cuando no corra jeager en local, 
# otel.traces.exporter=otlp
otel.traces.exporter=${OTEL_TRACES_EXPORTER:none}
otel.metrics.exporter=none
otel.logs.exporter=none

# Endpoint del collector (puede ser local o AWS X-Ray/otro backend)
otel.exporter.otlp.protocol=http/protobuf
otel.exporter.otlp.endpoint=http://localhost:4318

# Nombre del servicio
otel.resource.attributes=service.name=paypro