spring.application.name=paypro

# Configuración H2 en memoria
spring.datasource.url=jdbc:h2:mem:paypro;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true

# Consola H2 habilitada
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=mysuperlongsecretkeythatshouldbeatleast64byteslongandrandomtouseinthe512signaturealgorithm
jwt.expirationMs=86400000
server.port=8080

paypro.api-key=secret123
# paypro:
#   api-key: secret123

# Apagar SQL en dev
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF
logging.level.org.hibernate.engine.jdbc.spi.SqlStatementLogger=OFF

# Habilitar tracing - opentelemtry - ver en http://localhost:16686/
#deshabilitar cuando no corra jeager en local, 
# otel.traces.exporter=otlp
otel.traces.exporter=${OTEL_TRACES_EXPORTER:none}
otel.metrics.exporter=none
otel.logs.exporter=none

# Endpoint del collector (puede ser local o AWS X-Ray/otro backend)
otel.exporter.otlp.protocol=http/protobuf
otel.exporter.otlp.endpoint=http://localhost:4318

# Nombre del servicio
otel.resource.attributes=service.name=paypro

account.service.url=http://localhost:8081
provider.service.url=http://localhost:8082

aws.sqs.queue.url=https://sqs.us-east-1.amazonaws.com/781195019885/paypro-notifications
aws.region=us-east-1

# Circuit Breaker - provider-service
resilience4j.circuitbreaker.instances.providerService.sliding-window-size=5
resilience4j.circuitbreaker.instances.providerService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.providerService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.providerService.permitted-number-of-calls-in-half-open-state=2

# Circuit Breaker - account-service
resilience4j.circuitbreaker.instances.accountService.sliding-window-size=5
resilience4j.circuitbreaker.instances.accountService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.accountService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.accountService.permitted-number-of-calls-in-half-open-state=2

# Retry
resilience4j.retry.instances.providerService.max-attempts=3
resilience4j.retry.instances.providerService.wait-duration=500ms
resilience4j.retry.instances.accountService.max-attempts=3
resilience4j.retry.instances.accountService.wait-duration=500ms

# Timeout
resilience4j.timelimiter.instances.providerService.timeout-duration=3s
resilience4j.timelimiter.instances.accountService.timeout-duration=3s

# no reintente cuando el circuito está abierto
resilience4j.retry.instances.accountService.ignore-exceptions=io.github.resilience4j.circuitbreaker.CallNotPermittedException