spring.application.name=paypro
# descomentar para correr en local
# spring.profiles.active=dev

# paypro.api-key=secret123

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
# spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
# Desactiva el log de SQL
spring.jpa.show-sql=false

paypro.api-key=${PAYPRO_API_KEY}

logging.level.root=INFO
logging.level.com.ciberaccion.paypro.filter=INFO
logging.level.com.ciberaccion.paypro=DEBUG
# Formato de log personalizado
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %5p %logger{0} - %msg%n

# Apaga el logger que imprime las sentencias SQL
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF
logging.level.org.hibernate.engine.jdbc.spi.SqlStatementLogger=OFF

# Observability
# micrometrer
management.endpoints.web.exposure.include=health,info,metrics
management.metrics.export.cloudwatch.namespace=PayProMetrics
management.metrics.export.cloudwatch.step=1m

# Telemetry
# ver en AWS-xray las trazas
# otel.traces.exporter=otlp
otel.traces.exporter=${OTEL_TRACES_EXPORTER:none}
otel.metrics.exporter=none
otel.logs.exporter=none
otel.exporter.otlp.protocol=http/protobuf
# En AWS
otel.exporter.otlp.endpoint=adot-collector:4318
# En Local, corriendo app endockers apuntamos el jaeger server a localhost
# otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}
otel.resource.attributes=service.name=paypro

account.service.url=${ACCOUNT_SERVICE_URL}
provider.service.url=${PROVIDER_SERVICE_URL}